version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/danesparza/net-version
    steps:
      - checkout

      # specify any bash command here prefixed with `run: `
      - run: go get github.com/mitchellh/gox
      - run: go get github.com/tcnksm/ghr

      - run: env GOOS=windows go get -d -v ./...
      - run: gox -os="windows" -output "/tmp/net-version_{{.OS}}_{{.Arch}}"

      # Indicate we have artifacts
      - store_artifacts:
          path: /tmp

      # Create a release
      - run: 
         name: Push the release to Github
         command: ghr -t $GITHUB_TOKEN -u $CIRCLE_PROJECT_USERNAME -r $CIRCLE_PROJECT_REPONAME v1.0.$CIRCLE_BUILD_NUM /tmp || true